---
- name: Create and Set Hashed Password for Ansible User
  hosts: your_target_hosts
  become: true
  vars:
    username_to_create: "ansible"
    hashed_password: "$6$UhLSM2nOzAdkQ$joiRo0yUHv4x8Efe/nBklhrqnnoR6G.6LwdlL78Qm7hK9lSJu4d7RdvswuU7wgXUAWoCDZbyke.iZGFcy1w6P/"
  tasks:
    - name: Create ansible user
      user:
        name: "{{ username_to_create }}"
        password: "{{ hashed_password }}"
        shell: /bin/bash
        createhome: yes
      become: true

    - name: Set hashed password for ansible user
      user:
        name: "{{ username_to_create }}"
        password: "{{ hashed_password }}"
      become: true

