---
- name: Proxmox stuff
  hosts: all
  tasks: 

    - name: Clone VM
      proxmox_kvm:
        api_user    : root@pam
        api_password: '{{ pass }}'
        api_host    : 10.10.0.3
        clone       : template   # The VM source
        name        : ubuntu-template  # The target VM name
        node        : DarthVader
        storage     : local-lvm
        format      : qcow2
        timeout     : 500  # Note: The task can take a while. Adapt

    - name: Start VM
      proxmox_kvm:
        api_user    : root@pam
        api_password: '{{ pass }}'
        api_host    : 10.10.0.3
        name        : ubuntu-template
        node        : DarthVader
        state       : started
        timeout     : 500
        
    - name: Gather facts about the VM
      proxmox:
       api_user    : root@pam
       api_password: "pass"  # Use quotes for strings
       api_host    : 10.10.0.3
       node        : DarthVader
       command     : get
       path        : /nodes/DarthVader/qemu/{{ vm_result.ansible_proxmox_vm.vmid }}/config
     register: vm_info
