---
- name: Create Ansible User with Admin Rights
  hosts: all
  become: true
  tasks:
    - name: Create ansible user
      user:
        name: ansible
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    - name: Add ansible user to sudoers file
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^ansible'
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: true
